"""update_vector_dims

Revision ID: 722eb74487fd
Revises: b31050ea7a0a
Create Date: 2025-02-02 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector # Safe import

# revision identifiers, used by Alembic.
revision: str = '722eb74487fd'
down_revision: Union[str, None] = 'b31050ea7a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_signals', 'embedding',
               existing_type=Vector(768),
               type_=Vector(1536),
               existing_nullable=True,
               postgresql_using='embedding::vector(1536)')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_signals', 'embedding',
               existing_type=Vector(1536),
               type_=Vector(768),
               existing_nullable=True,
               postgresql_using='embedding::vector(768)')