"""initial_schema

Revision ID: 867f42836294
Revises: 
Create Date: 2026-01-12 14:55:15.394468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '867f42836294'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable vector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_signals',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('strategy_os',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('raw_doc_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_table('strategy_objectives',
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('owner_role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_os.strategy_id'], ),
    sa.PrimaryKeyConstraint('objective_id')
    )
    op.create_table('strategy_recommendations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('trigger_signal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trigger_signal_id'], ['external_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('impact_ledger_strategy',
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('expected_roi', sa.String(), nullable=True),
    sa.Column('actual_roi', sa.String(), nullable=True),
    sa.Column('kpi_impacted', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['strategy_recommendations.recommendation_id'], ),
    sa.PrimaryKeyConstraint('ledger_id')
    )
    op.create_table('strategy_kpis',
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['strategy_objectives.objective_id'], ),
    sa.PrimaryKeyConstraint('kpi_id')
    )
    op.create_table('internal_signals',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('kpi_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['strategy_kpis.kpi_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internal_signals')
    op.drop_table('strategy_kpis')
    op.drop_table('impact_ledger_strategy')
    op.drop_table('strategy_recommendations')
    op.drop_table('strategy_objectives')
    op.drop_table('strategy_os')
    op.drop_table('external_signals')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
