"""add_severity_and_impact

Revision ID: b98c823272da
Revises: 867f42836294
Create Date: 2026-01-12 15:10:36.366398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98c823272da'
down_revision: Union[str, Sequence[str], None] = '867f42836294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_signals', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('strategy_recommendations', sa.Column('impact_estimate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_recommendations', 'impact_estimate')
    op.drop_column('external_signals', 'severity')
    # ### end Alembic commands ###
